<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>NU1507</NoWarn>

    <MicrosoftCodeAnalysisVersion>5.10.0-1.26352.10</MicrosoftCodeAnalysisVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Features" Version="$(MicrosoftCodeAnalysisVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.LanguageServer.Protocol" Version="$(MicrosoftCodeAnalysisVersion)" />
    <PackageVersion Include="Microsoft.CommonLanguageServerProtocol.Framework" Version="$(MicrosoftCodeAnalysisVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.ExternalAccess.CompilerDeveloperSdk" Version="$(MicrosoftCodeAnalysisVersion)" />
    <PackageVersion Include="ICSharpCode.Decompiler" Version="9.1.0.7988" />
    <PackageVersion Include="MessagePack" Version="2.5.302" />
  </ItemGroup>
</Project>
