<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)\..\..\Microsoft.CodeAnalysis.CompilerDeveloperSDK.snk</AssemblyOriginatorKeyFile>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.CodeAnalysis.LanguageServer.Protocol" ExcludeAssets="runtime" />

    <PackageReference Include="Microsoft.CodeAnalysis.ExternalAccess.CompilerDeveloperSdk" ExcludeAssets="runtime" />
    <PackageReference Include="ICSharpCode.Decompiler" ExcludeAssets="runtime" GeneratePathProperty="true" />
  </ItemGroup>

  <Target Name="VscePrepublish" DependsOnTargets="Build">

    <Delete Files="$(MSBuildThisFileDirectory)..\..\dist\Microsoft.CodeAnalysis.ExternalAccess.CompilerDeveloperSDK.dll" />

    <Copy
        SourceFiles="$(TargetPath);$(PkgICSharpCode_Decompiler)\lib\netstandard2.0\ICSharpCode.Decompiler.dll"
        DestinationFolder="$(MSBuildThisFileDirectory)..\..\dist">
    </Copy>
  </Target>

</Project>
