# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install VSCE
      run: npm install @vscode/vsce -g --save-dev
    - name: Restore dependencies
      run: dotnet restore -bl:logs\Restore.binlog
    - name: Build
      run: dotnet build --no-restore -bl:logs\Build.binlog
    - name: Test
      run: dotnet test --no-build --verbosity normal -bl:logs\Test.binlog
    - run: npm ci
    - run: npm run compile
    - run: vsce package
    - name: Archive logs
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: |
          logs
    - name: Archive VSIX
      uses: actions/upload-artifact@v3
      with:
        name: vsix
        path: |
          *.vsix
